config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations'}


  root to: 'songs#home_page'

  resources :users
  get 'users/:id/info', to: 'users#info'
  get '/all_users', to: 'users#all_users'

  resources :songs
  get 'songs/:id/info', to: 'songs#info'
  get '/unfinished_songs', to: 'songs#unfinished_songs'
  get '/finished_songs', to: 'songs#finished_songs'
  patch '/songs/:id/finish', to: 'songs#finish'
  patch '/songs/:id/reopen', to: 'songs#reopen'

  resources :feature_tracks, only: [:create, :destroy]
  resources :master_tracks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: :create
  delete '/likes', to: 'likes#destroy'
  resources :connections, only: :create
  delete '/connections', to: 'connections#destroy'


  post 'talents/genres_talents', to: 'talents#create_genres_talents'

end

app/models/song.rb
class Song < ApplicationRecord
  include ActiveModel::Serializers::JSON
  # Connects song to owner
  belongs_to :user, foreign_key: :owner_id

  # Connects song to master tracks and feature tracks included in them
  # The association between the song and its included feature tracks is done
  # individually through each master track.
  has_many :master_tracks, dependent: :destroy

  # Connects song to submitted feature tracks
  has_many :feature_tracks, dependent: :destroy

  # Connects song to genres
  has_many :song_genres, dependent: :destroy
  has_many :genres, through: :song_genres

  # Connects song to desired talents
  has_many :song_talents, dependent: :destroy
  has_many :desired_talents, through: :song_talents, source: :talent

  validates :bpm, :key, :time_signature, :title, presence: true
  validates :time_signature, format: { with: /\d\/\d/, message: "must include at least one time signature with beats per bar over note value per beat, e.g.: 3/4 or 4/4" }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  GENERIC_SONG_IMAGES = ["https://jamsession-app.s3.amazonaws.com/Pearl1.jpg", "https://jamsession-app.s3.amazonaws.com/Pearl2.jpg", "https://jamsession-app.s3.amazonaws.com/Pearl3.jpg", "https://jamsession-app.s3.amazonaws.com/Pearl4.jpg", "https://jamsession-app.s3.amazonaws.com/Pearl5.jpg","https://jamsession-app.s3.amazonaws.com/Pearl6.jpg"]

  def finished_songs
    finished_songs = Song.where(finished: true)
    render json: finished_songs.as_json(include: [ :genres, :desired_talents, {master_tracks: {include: :likes}}, :user])
  end

  def unfinished_songs
    unfinished_songs = Song.where(finished: false)
    render json: unfinished_songs.as_json(include: [:desired_talents, :genres, {master_tracks: {include: :likes}}, :user])
  end

  def home_page
    if current_user
      user = User.find(current_user.id)
      @user_talents = user.talents
      @logged_in = true if user_signed_in?
      @user_genres = user.genres.map(&:name)
      @user_talents = user.talents.map(&:title)
    end
  end

  def show
    song = Song.find(params[:id])
    user = User.find(song.owner_id)
    @private_user_auth = false
    if current_user && song.owner_id == current_user.id
      @private_user_auth = true
    end
  end

  def info
    song = Song.find(params[:id])
    song_as_json(song)
  end

  def create
    # Create error array
    @errors = []

    # Create a new song
    @song = Song.new(title: params[:title], owner_id: params[:owner_id], bpm: params[:bpm], key: params[:key], time_signature: params[:time_signature], background: params[:background])
    @song.finished = false

    # Add genres to song
    genre_params = params.keys.select { |param| param =~ /genre/ }
    genre_ids = genre_params.map { |name| name.gsub(/genre/, "").to_i }
    genres_to_add = genre_ids.map { |id| Genre.find(id) }
    genres_to_add.each do |genre|
      @song.genres << genre
    end

    if @song.genres.length > 0
      song_has_genres = true
    else
      @errors << "Song must have at least one genre"
    end

    # Add talents to song
    talent_params = params.keys.select { |param| param =~ /talent/ }
    talent_ids = talent_params.map { |name| name.gsub(/talent/, "").to_i }
    talents_to_add = talent_ids.map { |id| Talent.find(id) }
    talents_to_add.each do |talent|
      @song.desired_talents << talent
    end

    if @song.desired_talents.length > 0
      song_has_talents = true
    else
      @errors << "Song must have at least one desired talent"
    end

    # Check for file
    if params[:file]
      song_has_file = true
    else
      @errors << "Song must have an initial master track"
    end

    if @song.save && song_has_talents && song_has_genres && song_has_file
      # Create initial master track
      s3 = AWS::S3.new(:access_key_id => ENV['ACCESS_KEY_ID'], :secret_access_key => ENV['SECRET_ACCESS_KEY'])

      obj = s3.buckets[ENV['S3_BUCKET']].objects[params[:file].original_filename]

      obj.write(
        file: params[:file],
        acl: :public_read
      )

      master_track = @song.master_tracks.new(description: params[:description])

      master_track.file_name = obj.key
      master_track.file_path = obj.public_url

      master_track.save

      # Create song image or give a random picture
      if params[:img_file]  
        img = s3.buckets[ENV['S3_BUCKET']].objects[params[:img_file].original_filename]

        img.write(
          file: params[:img_file],
          acl: :public_read
        )

        @song.img_file_name = img.key
        @song.img_file_path = img.public_url
      else
        @song.img_file_name = "default"
        @song.img_file_path = GENERIC_SONG_IMAGES.sample
      end

      # Save song with file and image
      @song.save

      # Redirect user to new song page
      redirect_to "/songs/#{@song.id}"
    else
      @errors << @song.errors.full_messages
      @errors = @errors.flatten
      @description = params[:description]
      @current_user = current_user
      @genres = Genre.all.order(:name)
      @talents = Talent.all.order(:title)
      render 'songs/new'
    end
  end

  def update
    song = Song.find(params[:id])
    song.update(song_params)

    # Resets the song's genres according to user's new choices
    SongGenre.where(song_id: song.id).destroy_all
    params[:songGenres].each do |genre_id|
      song.genres << Genre.find(genre_id.to_i)
    end

    # Resets the song's desired talents according to user's new choices
    SongTalent.where(song_id: song.id).destroy_all
    params[:desiredTalents].each do |talent_id|
      song.desired_talents << Talent.find(talent_id.to_i)
    end

    song_as_json(song)
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy
    redirect_to root_path, status: 303
  end

  def new
    @song = Song.new
    @genres = Genre.all.order(:name)
    @talents = Talent.all.order(:title)
    @current_user = current_user
  end

  def finish
    song = Song.find(params[:id])
    song.finished = true
    song.save
    song_as_json(song)
  end

  def reopen
    song = Song.find(params[:id])
    song.finished = false
    song.save
    song_as_json(song)
  end

  private
  def song_as_json(song)
    render json: song.as_json(include:
      [{master_tracks: { include:
        [{feature_tracks: { include: [:user, :talent]}},
        {comments: { include: :user }},
        :likes,
        :fans]}},
      :user,
      :genres,
      :desired_talents,
      feature_tracks: { include: [:user, :talent]}])
  end

  def song_params
    params.require(:song).permit(:title, :bpm, :key, :background, :time_signature)
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/home_page.html.erb
<%= react_component('DisplayedSong', user_genres: @user_genres, user_talents: @user_talents) %>


   <% form_tag(users_path, :method => "get", id: "search-form", :class => "navbar-brand top_margin") do %>
          <%= text_field :search, params[:search], placeholder: "Search Users" %>
          <%= submit_tag "Search"%>
        <% end %>

app/views/songs/index.html.erb
<%= react_component 'DisplayedSong'%>

app/views/songs/new.html.erb
<br>
<div class="border-form-div new_project">
<h1>Begin a New Project</h1>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li class="error-text"><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag songs_path, enctype: 'multipart/form-data' do %>
  <!-- Song information here -->
  <%= hidden_field_tag :owner_id, @current_user.id %>
  <%= label_tag :title, "Title" %><br>
  <%= text_field_tag :title, @song.title %><br>
  <%= label_tag :bpm, "BPM" %><br>
  <%= text_field_tag :bpm, @song.bpm %><br>
  <%= label_tag :key, "Key" %><br>
  <%= text_field_tag :key, @song.key %><br>
  <%= label_tag :time_signature, "Time Signature" %><br>
  <%= text_field_tag :time_signature, @song.time_signature %><br>
  <%= label_tag :background, "Enter song's background information here" %><br>
  <%= text_area_tag :background, @song.background %><br>
  <%= label_tag :img_file, "Upload an image for your song here" %>
  <%= file_field_tag :img_file %><br>

  <!-- Song's genres here -->
  <h3>Choose all genres for this song</h3>
  <% @genres.each do |genre| %>
    <%= check_box_tag "genre#{genre.id}", 1, @song.genres.include?(genre) ? true : false %>
    <%= label_tag :genre, "#{genre.name}" %><br>
  <% end %>

  <!-- Song's desired talents here -->
  <h3>Choose all desired talents for this song</h3>
  <% @talents.each do |talent| %>
    <%= check_box_tag "talent#{talent.id}", 1, @song.desired_talents.include?(talent) ? true : false %>
    <%= label_tag :talent, "#{talent.title}" %><br>
  <% end %>

  <!-- Initial master track here -->
  <h3>Fill out initial master track information here</h3>
  <%= label_tag :description, "Enter master track's description here" %><br>
  <%= text_area_tag :description, @description ? @description : "" %><br>
  <%= label_tag :file, "Upload initial master file" %><br>
  <%= file_field_tag :file %><br>

  <!-- Submit button -->
  <%= submit_tag value="Start Project",:class=>'btn btn-primary' %>
<% end %>
</div>
<br>

app/views/songs/show.html.erb
<%= react_component('SongPage', private_user_auth: @private_user_auth, song_id: params[:id], currentUser: current_user, allGenres: Genre.all, allTalents: Talent.all) %>