config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'registrations'}


  root to: 'songs#home_page'

  resources :users
  get 'users/:id/info', to: 'users#info'
  get '/all_users', to: 'users#all_users'

  resources :songs
  get 'songs/:id/info', to: 'songs#info'
  get '/unfinished_songs', to: 'songs#unfinished_songs'
  get '/finished_songs', to: 'songs#finished_songs'
  patch '/songs/:id/finish', to: 'songs#finish'
  patch '/songs/:id/reopen', to: 'songs#reopen'

  resources :feature_tracks, only: [:create, :destroy]
  resources :master_tracks, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: :create
  delete '/likes', to: 'likes#destroy'
  resources :connections, only: :create
  delete '/connections', to: 'connections#destroy'


  post 'talents/genres_talents', to: 'talents#create_genres_talents'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActiveModel::Serializers::JSON

  # Connects comment to user
  belongs_to :user

  # Connects comment to master track
  belongs_to :master_track

  validates :body, presence: true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/feature_track.rb
class FeatureTrack < ApplicationRecord
  # Connects a feature track to a user for a specific talent
  belongs_to :user
  belongs_to :talent

  # Connects the feature track to whichever master tracks it is included in
  has_many :master_features, dependent: :destroy
  has_many :master_tracks, through: :master_features

  # Connect the feature track to the song
  belongs_to :song
end

app/models/genre.rb
class Genre < ApplicationRecord
  # Connects the genres to users
  has_many :user_genres
  has_many :users, through: :user_genres

  # Connects the genres to songs
  has_many :song_genres
  has_many :songs, through: :song_genres
end

app/models/like.rb
class Like < ApplicationRecord
  # Connects like to user and master track
  belongs_to :user
  belongs_to :master_track
end

app/models/master_feature.rb
class MasterFeature < ApplicationRecord
  # Connects master and features
  belongs_to :master_track
  belongs_to :feature_track
end

app/models/master_track.rb
class MasterTrack < ApplicationRecord
  # Connects master track to song and owner of song
  belongs_to :song
  has_one :song_owner, through: :song, source: :user

  # Connects master track to feature tracks
  has_many :master_features, dependent: :destroy
  has_many :feature_tracks, through: :master_features

  # Connects master track to users who submitted feature tracks and the talents involved
  has_many :contributors, through: :feature_tracks, source: :user
  has_many :talents, through: :feature_tracks

  # Connects master track to comments
  has_many :comments, dependent: :destroy

  # Connects master track to people who liked it
  has_many :likes, dependent: :destroy
  has_many :fans, through: :likes, source: :user
end

app/models/song.rb
class Song < ApplicationRecord
  include ActiveModel::Serializers::JSON
  # Connects song to owner
  belongs_to :user, foreign_key: :owner_id

  # Connects song to master tracks and feature tracks included in them
  # The association between the song and its included feature tracks is done
  # individually through each master track.
  has_many :master_tracks, dependent: :destroy

  # Connects song to submitted feature tracks
  has_many :feature_tracks, dependent: :destroy

  # Connects song to genres
  has_many :song_genres, dependent: :destroy
  has_many :genres, through: :song_genres

  # Connects song to desired talents
  has_many :song_talents, dependent: :destroy
  has_many :desired_talents, through: :song_talents, source: :talent

  validates :bpm, :key, :time_signature, :title, presence: true
  validates :time_signature, format: { with: /\d\/\d/, message: "must include at least one time signature with beats per bar over note value per beat, e.g.: 3/4 or 4/4" }
end

app/models/song_genre.rb
class SongGenre < ApplicationRecord
  # Allow for songs to genres
  belongs_to :song
  belongs_to :genre
end

app/models/song_talent.rb
class SongTalent < ApplicationRecord
  # Allows for connection of song to talent
  belongs_to :song
  belongs_to :talent
end

app/models/talent.rb
class Talent < ApplicationRecord
  # Connects talents to songs desiring those talents
  has_many :song_talents
  has_many :songs, through: :song_talents

  # Connects talents to users with those talents 
  has_many :user_talents
  has_many :users, through: :user_talents

  has_many :feature_tracks
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::Serializers::JSON

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Sets up followers and following connections
  has_many :followed_connections, foreign_key: :follower_id, class_name: "Connection"
  has_many :follower_connections, foreign_key: :followed_id, class_name: "Connection"
  has_many :following, through: :followed_connections, source: :followed
  has_many :followers, through: :follower_connections, source: :follower

  # Sets up talents that user says they have upon signing up
  has_many :user_talents
  has_many :talents, through: :user_talents

  # Sets up users' preferred genres
  has_many :user_genres
  has_many :genres, through: :user_genres

  # Connects user to comment
  has_many :comments

  # Connets user to songs that they own
  has_many :songs, foreign_key: :owner_id

  # Sets up liking ability
  has_many :likes
  has_many :liked_tracks, through: :likes, source: :master_track

  # Sets up feature tracks and connections to collaborated tracks
  has_many :feature_tracks
  has_many :master_features, through: :feature_tracks
  has_many :master_tracks, through: :master_features
  has_many :collaborated_songs, through: :master_tracks, source: :song

  validates :email, format: { with: /\A\w+@\w+[.]\w+\z/, message: "must be a valid e-mail address" }
  validates :username, length: { maximum: 18, minimum: 6 }
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
  # Allows for connection between users and genres
  belongs_to :user
  belongs_to :genre
end

app/models/user_talent.rb
class UserTalent < ApplicationRecord
  # Allows for connection between users and talents
  belongs_to :user
  belongs_to :talent
end

app/controllers/app_controller.rb
class AppController < ApplicationController


  def index
  end


end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app/index.html.erb
<%= react_component 'UserPageView'%>

<!-- 
  <% form_tag(users_path, :method => "get", id: "search-form", :class => "navbar-brand top_margin") do %>
    <%= text_field :search, params[:search], placeholder: "Search Users" %>
    <%= submit_tag "Search"%>
  <% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jam Session</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- <link rel="stylesheet" type="text/css" href="userpage.css"> -->
    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified CSS -->

    <!-- jQuery library -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     -->
    <!-- Latest compiled JavaScript -->
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
    <link rel="stylesheet" href="http://www.atlasestateagents.co.uk/css/tether.min.css">
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- used for search-bar autofill grabbing jedWatson react-select -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.min.js"></script>
    <script src="https://unpkg.com/classnames/index.js"></script>
    <script src="https://unpkg.com/react-input-autosize/dist/react-input-autosize.js"></script>
    <script src="https://unpkg.com/react-select/dist/react-select.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/react-select/dist/react-select.css"> -->

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-select/0.9.1/react-select.min.js"></script> -->

    <!-- jquery-ui -->
      <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <!-- may need to remove -->
  </head>

  <body>

    <nav id="navigation-bar-top" class="navbar navbar-inverse no-border">


      <%= react_component "SearchBar" %>
      <% if flash[:notice] %>
        <div class="alert alert-warning">
          <%= flash[:notice]%>
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>
      <% end %>

        <a class="no-margin" href="/"><img class="site-logo" src="https://jamsession-app.s3.amazonaws.com/JamSessionLogo.png"><span class="site-name">JAMSession</span></a>


        <% if user_signed_in? %>

          <div class="nav-ul-holder">
            <ul class="nav-ul">
              <li><%= link_to current_user.username, user_path(current_user) %></li>
              <li><%= link_to "New Project", new_song_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>

        <% else %>

          <div class="nav-ul-holder">
            <ul class="nav-ul">
              <li><%= link_to "Sign In", new_user_session_path  %></li>
              <li><%= link_to "Register", new_user_registration_path %></li>
            </ul>
          </div>


        <% end %>


    </nav>




    <%= yield %>
  </body>
</html>